In [ ]:
import numpy as np
import math 

def rotation(vec,ang,axis):
    
    if ang < 0: # control mechanism for clockwise direction(clockwise is negative,counter-clockwise is positive)
        ang += 360
    else:
        pass
    ang=math.radians(ang) # here we converted values in degree to radians
    
    c,s=math.cos(ang),math.sin(ang)

    vec=np.array(vec).reshape(3,1) # adjustments for the vector entered to be in 3*1 format
    if axis == 1:  # according to axis value matrix multiplication
        return np.dot(np.array([
            [1 , 0 , 0],
            [0 , c , s],
            [0 , -s , c]
        ]),vec)
    elif axis == 2:
        return np.dot(np.array([
            [c , 0 , -s],
            [0 , 1 , 0],
            [s , 0 , c]
        ]),vec)
    elif axis == 3:
        return np.dot(np.array([
            [c , s , 0],
            [-s , c , 0],
            [0 , 0 , 1]
        ]),vec)
    else:
        raise ValueError("axis should in range")
 

In [33]:
rotation([100,120,200],-20,2)

array([[162.37329074],
       [120.        ],
       [153.73650982]])

In [30]:
rotation([162.37329074,120,153.73650982],25,3)

array([[197.87436921],
       [ 40.13501656],
       [153.73650982]])

In [31]:
rotation([197.87436921,40.13501656 ,153.73650982 ],7,2)

array([[177.66367616],
       [ 40.13501656],
       [176.70540064]])